DROP USER IF EXISTS transport;
CREATE USER transport WITH PASSWORD 'transport';
DROP DATABASE IF EXISTS transport;
CREATE DATABASE transport;
GRANT ALL PRIVILEGES ON DATABASE transport TO transport;

DROP USER IF EXISTS reservation;
CREATE USER reservation WITH PASSWORD 'reservation';
DROP DATABASE IF EXISTS reservation;
CREATE DATABASE reservation;
GRANT ALL PRIVILEGES ON DATABASE reservation TO reservation;

DROP USER IF EXISTS offers;
CREATE USER offers WITH PASSWORD 'offers';
DROP DATABASE IF EXISTS offers;
CREATE DATABASE offers;
GRANT ALL PRIVILEGES ON DATABASE offers TO offers;

DROP USER IF EXISTS hotels;
CREATE USER hotels WITH PASSWORD 'hotels';
DROP DATABASE IF EXISTS hotels;
CREATE DATABASE hotels;
GRANT ALL PRIVILEGES ON DATABASE hotels TO hotels;